#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: IPQ60xx_Package

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '30 2 * * *'
    - cron:  '30 8 * * *'

jobs:

  build_openwrt:
    name: Build IPQ60xx IPK
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          set +e
          docker rmi `docker images -q`
          echo "Deleting files, please wait ..."
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf wget swig rsync
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Clone source code
        env:
         REPO_URL: https://github.com/coolsnowwolf/lede
         REPO_BRANCH: master
        run: |
          git clone $REPO_URL -b $REPO_BRANCH openwrt
          
      - name: Update feeds
        working-directory: ./openwrt
        run: |
          rm -rf package/lean/luci-theme-argon
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git package/lean/luci-theme-argon
          git clone https://github.com/jerrykuku/luci-app-argon-config.git package/lean/luci-app-argon-config
          git clone https://github.com/thinktip/luci-theme-neobird.git package/lean/luci-theme-neobird
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          sed -i "/helloworld/d" "feeds.conf.default"
          echo "src-git helloworld https://github.com/fw876/helloworld.git" >> "feeds.conf.default"
          ./scripts/feeds update helloworld
          ./scripts/feeds install -a -f -p helloworld
          git clone https://github.com/jerrykuku/lua-maxminddb.git package/lean/lua-maxminddb
          git clone https://github.com/jerrykuku/luci-app-vssr.git package/lean/luci-app-vssr

      - name: Generate configuration file
        working-directory: ./openwrt
        run: |
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF
          CONFIG_TARGET_ipq60xx=y
          CONFIG_TARGET_ipq60xx_generic=y
          CONFIG_TARGET_ipq60xx_generic_Default=y
          CONFIG_BATMAN_ADV_BATMAN_V=y
          CONFIG_BATMAN_ADV_BLA=y
          CONFIG_BATMAN_ADV_DAT=y
          CONFIG_BATMAN_ADV_MCAST=y
          CONFIG_DISPLAY_SUPPORT=y
          CONFIG_HTOP_LMSENSORS=y
          CONFIG_KERNEL_KEXEC=y
          CONFIG_LIBMBEDTLS_HAVE_ARMV8CE_AES=y
          # CONFIG_OPENSSL_PREFER_CHACHA_OVER_GCM is not set
          CONFIG_PACKAGE_SAMBA_MAX_DEBUG_LEVEL=-1
          CONFIG_PACKAGE_UnblockNeteaseMusic-Go=y
          CONFIG_PACKAGE_adbyby=y
          CONFIG_PACKAGE_automount=y
          CONFIG_PACKAGE_autosamba=y
          CONFIG_PACKAGE_bash=y
          CONFIG_PACKAGE_batctl-default=y
          CONFIG_PACKAGE_bc=y
          CONFIG_PACKAGE_bnx2-firmware=y
          CONFIG_PACKAGE_bnx2x-firmware=y
          CONFIG_PACKAGE_boost=y
          CONFIG_PACKAGE_boost-date_time=y
          CONFIG_PACKAGE_boost-program_options=y
          CONFIG_PACKAGE_boost-system=y
          # CONFIG_PACKAGE_ca-certificates is not set
          CONFIG_PACKAGE_cfdisk=y
          CONFIG_PACKAGE_dawn=y
          CONFIG_PACKAGE_e2fsprogs=y
          CONFIG_PACKAGE_ethtool=y
          CONFIG_PACKAGE_frpc=y
          CONFIG_PACKAGE_hd-idle=y
          CONFIG_PACKAGE_hostapd-common=y
          CONFIG_PACKAGE_htop=y
          CONFIG_PACKAGE_i915-firmware=y
          CONFIG_PACKAGE_ipt2socks=y
          CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
          # CONFIG_PACKAGE_iptables-mod-extra is not set
          CONFIG_PACKAGE_iptables-mod-ipopt=y
          CONFIG_PACKAGE_iptables-mod-ipsec=y
          CONFIG_PACKAGE_iputils-arping=y
          CONFIG_PACKAGE_iw=y
          CONFIG_PACKAGE_iwinfo=y
          CONFIG_PACKAGE_jq=y
          CONFIG_PACKAGE_kcptun-client=y
          CONFIG_PACKAGE_kcptun-config=y
          CONFIG_PACKAGE_kmod-8139cp=y
          CONFIG_PACKAGE_kmod-8139too=y
          CONFIG_PACKAGE_kmod-alx=y
          CONFIG_PACKAGE_kmod-batman-adv=y
          CONFIG_PACKAGE_kmod-bnx2=y
          CONFIG_PACKAGE_kmod-bnx2x=y
          CONFIG_PACKAGE_kmod-bonding=y
          CONFIG_PACKAGE_kmod-button-hotplug=y
          CONFIG_PACKAGE_kmod-cfg80211=y
          CONFIG_PACKAGE_kmod-crypto-cbc=y
          CONFIG_PACKAGE_kmod-crypto-crc32=y
          CONFIG_PACKAGE_kmod-crypto-crc32c=y
          CONFIG_PACKAGE_kmod-crypto-deflate=y
          CONFIG_PACKAGE_kmod-crypto-des=y
          CONFIG_PACKAGE_kmod-crypto-echainiv=y
          CONFIG_PACKAGE_kmod-crypto-hmac=y
          CONFIG_PACKAGE_kmod-crypto-kpp=y
          CONFIG_PACKAGE_kmod-crypto-lib-blake2s=y
          CONFIG_PACKAGE_kmod-crypto-lib-chacha20=y
          CONFIG_PACKAGE_kmod-crypto-lib-chacha20poly1305=y
          CONFIG_PACKAGE_kmod-crypto-lib-curve25519=y
          CONFIG_PACKAGE_kmod-crypto-lib-poly1305=y
          CONFIG_PACKAGE_kmod-crypto-md5=y
          CONFIG_PACKAGE_kmod-dma-buf=y
          CONFIG_PACKAGE_kmod-drm=y
          CONFIG_PACKAGE_kmod-drm-kms-helper=y
          CONFIG_PACKAGE_kmod-drm-ttm=y
          CONFIG_PACKAGE_kmod-e1000=y
          CONFIG_PACKAGE_kmod-e1000e=y
          CONFIG_PACKAGE_kmod-fb=y
          CONFIG_PACKAGE_kmod-fb-cfb-copyarea=y
          CONFIG_PACKAGE_kmod-fb-cfb-fillrect=y
          CONFIG_PACKAGE_kmod-fb-cfb-imgblt=y
          CONFIG_PACKAGE_kmod-fb-sys-fops=y
          CONFIG_PACKAGE_kmod-fb-sys-ram=y
          CONFIG_PACKAGE_kmod-forcedeth=y
          CONFIG_PACKAGE_kmod-fs-exfat=y
          CONFIG_PACKAGE_kmod-fs-ext4=y
          CONFIG_PACKAGE_kmod-fs-f2fs=y
          CONFIG_PACKAGE_kmod-fs-ntfs3-oot=y
          CONFIG_PACKAGE_kmod-fs-vfat=y
          # CONFIG_PACKAGE_kmod-gpio-button-hotplug is not set
          CONFIG_PACKAGE_kmod-hid=y
          CONFIG_PACKAGE_kmod-hid-generic=y
          CONFIG_PACKAGE_kmod-hwmon-core=y
          CONFIG_PACKAGE_kmod-i2c-algo-bit=y
          CONFIG_PACKAGE_kmod-i2c-core=y
          CONFIG_PACKAGE_kmod-i40e=y
          CONFIG_PACKAGE_kmod-iavf=y
          CONFIG_PACKAGE_kmod-igb=y
          CONFIG_PACKAGE_kmod-igc=y
          CONFIG_PACKAGE_kmod-inet-diag=y
          CONFIG_PACKAGE_kmod-input-core=y
          CONFIG_PACKAGE_kmod-input-evdev=y
          CONFIG_PACKAGE_kmod-ipsec=y
          CONFIG_PACKAGE_kmod-ipsec4=y
          CONFIG_PACKAGE_kmod-ipsec6=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
          # CONFIG_PACKAGE_kmod-ipt-extra is not set
          CONFIG_PACKAGE_kmod-ipt-ipopt=y
          CONFIG_PACKAGE_kmod-ipt-ipsec=y
          CONFIG_PACKAGE_kmod-iptunnel4=y
          CONFIG_PACKAGE_kmod-iptunnel6=y
          CONFIG_PACKAGE_kmod-ixgbe=y
          # CONFIG_PACKAGE_kmod-leds-gpio is not set
          CONFIG_PACKAGE_kmod-lib-crc16=y
          CONFIG_PACKAGE_kmod-lib-crc32c=y
          CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
          CONFIG_PACKAGE_kmod-lib-zlib-inflate=y
          CONFIG_PACKAGE_kmod-libphy=y
          CONFIG_PACKAGE_kmod-mdio=y
          CONFIG_PACKAGE_kmod-mdio-devres=y
          CONFIG_PACKAGE_kmod-mii=y
          CONFIG_PACKAGE_kmod-mlx4-core=y
          CONFIG_PACKAGE_kmod-mlx5-core=y
          CONFIG_PACKAGE_kmod-mmc=y
          CONFIG_PACKAGE_kmod-nls-base=y
          CONFIG_PACKAGE_kmod-nls-cp437=y
          CONFIG_PACKAGE_kmod-nls-iso8859-1=y
          CONFIG_PACKAGE_kmod-nls-utf8=y
          CONFIG_PACKAGE_kmod-pcnet32=y
          CONFIG_PACKAGE_kmod-pps=y
          CONFIG_PACKAGE_kmod-ptp=y
          CONFIG_PACKAGE_kmod-r8125=y
          CONFIG_PACKAGE_kmod-r8168=y
          CONFIG_PACKAGE_kmod-scsi-core=y
          CONFIG_PACKAGE_kmod-sdhci=y
          CONFIG_PACKAGE_kmod-tulip=y
          CONFIG_PACKAGE_kmod-udptunnel4=y
          CONFIG_PACKAGE_kmod-udptunnel6=y
          CONFIG_PACKAGE_kmod-usb-core=y
          CONFIG_PACKAGE_kmod-usb-hid=y
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-asix-ax88179=y
          CONFIG_PACKAGE_kmod-usb-net-rtl8150=y
          CONFIG_PACKAGE_kmod-usb-storage=y
          CONFIG_PACKAGE_kmod-usb-storage-extras=y
          CONFIG_PACKAGE_kmod-usb-storage-uas=y
          CONFIG_PACKAGE_kmod-via-velocity=y
          CONFIG_PACKAGE_kmod-vmxnet3=y
          CONFIG_PACKAGE_kmod-wireguard=y
          CONFIG_PACKAGE_libblkid=y
          CONFIG_PACKAGE_libcap=y
          CONFIG_PACKAGE_libcares=y
          CONFIG_PACKAGE_libcomerr=y
          CONFIG_PACKAGE_libeudev=y
          CONFIG_PACKAGE_libext2fs=y
          CONFIG_PACKAGE_libf2fs=y
          CONFIG_PACKAGE_libfdisk=y
          CONFIG_PACKAGE_libgcrypt=y
          CONFIG_PACKAGE_libgmp=y
          CONFIG_PACKAGE_libgpg-error=y
          CONFIG_PACKAGE_libkmod=y
          CONFIG_PACKAGE_libmaxminddb=y
          CONFIG_PACKAGE_libmbedtls=y
          CONFIG_PACKAGE_libminiupnpc=y
          CONFIG_PACKAGE_libmount=y
          CONFIG_PACKAGE_libnatpmp=y
          CONFIG_PACKAGE_libncurses=y
          CONFIG_PACKAGE_libpci=y
          CONFIG_PACKAGE_libreadline=y
          CONFIG_PACKAGE_libsensors=y
          CONFIG_PACKAGE_libsmartcols=y
          CONFIG_PACKAGE_libss=y
          CONFIG_PACKAGE_libstdcpp=y
          CONFIG_PACKAGE_libsysfs=y
          CONFIG_PACKAGE_libusb-1.0=y
          CONFIG_PACKAGE_libuv=y
          CONFIG_PACKAGE_libwebsockets-full=y
          CONFIG_PACKAGE_lm-sensors=y
          CONFIG_PACKAGE_lua-cjson=y
          CONFIG_PACKAGE_lua-maxminddb=y
          CONFIG_PACKAGE_luasocket=y
          CONFIG_PACKAGE_luci-app-adbyby-plus=y
          CONFIG_PACKAGE_luci-app-argon-config=y
          CONFIG_PACKAGE_luci-app-cpufreq=y
          CONFIG_PACKAGE_luci-app-dawn=y
          CONFIG_PACKAGE_luci-app-easymesh=y
          CONFIG_PACKAGE_luci-app-frpc=y
          CONFIG_PACKAGE_luci-app-hd-idle=y
          CONFIG_PACKAGE_luci-app-ipsec-vpnd=y
          CONFIG_PACKAGE_luci-app-mwan3=y
          CONFIG_PACKAGE_luci-app-mwan3helper=y
          CONFIG_PACKAGE_luci-app-netdata=y
          CONFIG_PACKAGE_luci-app-pushbot=y
          CONFIG_PACKAGE_luci-app-ramfree=y
          CONFIG_PACKAGE_luci-app-samba=y
          CONFIG_PACKAGE_luci-app-serverchan=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_IPT2Socks=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Libev_Server=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Libev_Client=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Libev_Server=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Rust_Client is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Rust_Server is not set
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Simple_Obfs=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-unblockmusic=y
          # CONFIG_PACKAGE_luci-app-unblockmusic_INCLUDE_UnblockNeteaseMusic_Go is not set
          CONFIG_PACKAGE_luci-app-uugamebooster=y
          CONFIG_PACKAGE_luci-app-vssr=y
          CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Kcptun=y
          CONFIG_PACKAGE_luci-app-watchcat=y
          CONFIG_PACKAGE_luci-app-wireguard=y
          CONFIG_PACKAGE_luci-app-wrtbwmon=y
          CONFIG_PACKAGE_luci-app-xlnetacc=y
          CONFIG_PACKAGE_luci-app-zerotier=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_luci-i18n-adbyby-plus-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-argon-config-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-bonding-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-cpufreq-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-dawn-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-easymesh-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-frpc-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-hd-idle-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ipsec-vpnd-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-mwan3-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-mwan3helper-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-netdata-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ramfree-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-samba-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-unblockmusic-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-uugamebooster-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-vssr-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-watchcat-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wireguard-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wrtbwmon-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-xlnetacc-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-zerotier-zh-cn=y
          CONFIG_PACKAGE_luci-lib-json=y
          CONFIG_PACKAGE_luci-proto-bonding=y
          CONFIG_PACKAGE_luci-proto-wireguard=y
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-theme-material=y
          CONFIG_PACKAGE_luci-theme-neobird=y
          CONFIG_PACKAGE_luci-theme-netgear=y
          CONFIG_PACKAGE_mkf2fs=y
          CONFIG_PACKAGE_mwan3=y
          CONFIG_PACKAGE_netdata=y
          CONFIG_PACKAGE_ntfs3-mount=y
          CONFIG_PACKAGE_partx-utils=y
          CONFIG_PACKAGE_pciids=y
          CONFIG_PACKAGE_pciutils=y
          CONFIG_PACKAGE_proto-bonding=y
          CONFIG_PACKAGE_samba36-server=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-local=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-redir=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-server=y
          # CONFIG_PACKAGE_shadowsocks-rust-sslocal is not set
          # CONFIG_PACKAGE_shadowsocks-rust-ssserver is not set
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-server=y
          CONFIG_PACKAGE_simple-obfs-client=y
          CONFIG_PACKAGE_strongswan=y
          CONFIG_PACKAGE_strongswan-charon=y
          CONFIG_PACKAGE_strongswan-ipsec=y
          CONFIG_PACKAGE_strongswan-minimal=y
          CONFIG_PACKAGE_strongswan-mod-aes=y
          CONFIG_PACKAGE_strongswan-mod-gmp=y
          CONFIG_PACKAGE_strongswan-mod-hmac=y
          CONFIG_PACKAGE_strongswan-mod-kernel-libipsec=y
          CONFIG_PACKAGE_strongswan-mod-kernel-netlink=y
          CONFIG_PACKAGE_strongswan-mod-nonce=y
          CONFIG_PACKAGE_strongswan-mod-pubkey=y
          CONFIG_PACKAGE_strongswan-mod-random=y
          CONFIG_PACKAGE_strongswan-mod-sha1=y
          CONFIG_PACKAGE_strongswan-mod-socket-default=y
          CONFIG_PACKAGE_strongswan-mod-stroke=y
          CONFIG_PACKAGE_strongswan-mod-updown=y
          CONFIG_PACKAGE_strongswan-mod-x509=y
          CONFIG_PACKAGE_strongswan-mod-xauth-generic=y
          CONFIG_PACKAGE_strongswan-mod-xcbc=y
          CONFIG_PACKAGE_sysfsutils=y
          CONFIG_PACKAGE_terminfo=y
          CONFIG_PACKAGE_trojan=y
          CONFIG_PACKAGE_ttyd=y
          CONFIG_PACKAGE_umdns=y
          CONFIG_PACKAGE_usbids=y
          CONFIG_PACKAGE_usbutils=y
          CONFIG_PACKAGE_uugamebooster=y
          CONFIG_PACKAGE_watchcat=y
          CONFIG_PACKAGE_wireguard-tools=y
          CONFIG_PACKAGE_wireless-regdb=y
          CONFIG_PACKAGE_wpad-openssl=y
          CONFIG_PACKAGE_wsdd2=y
          CONFIG_PACKAGE_xray-plugin=y
          CONFIG_PACKAGE_zerotier=y
          CONFIG_STRONGSWAN_ROUTING_TABLE="220"
          CONFIG_STRONGSWAN_ROUTING_TABLE_PRIO="220"
          # CONFIG_TARGET_ROOTFS_INITRAMFS is not set
          CONFIG_WPA_MSG_MIN_PRIORITY=3
          CONFIG_boost-compile-visibility-hidden=y
          CONFIG_boost-runtime-shared=y
          CONFIG_boost-static-and-shared-libs=y
          CONFIG_boost-variant-release=y
          EOF
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        working-directory: ./openwrt
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h

      - name: Compile process
        working-directory: ./openwrt
        id : compile
        run: | 
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          du -h ./ --max-depth=1

      - name: Prepare artifact
        working-directory: ./openwrt
        id: artifact
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
          mkdir -p ./artifact/package
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          # curl -sX POST "https://bark.icolak.com/${{ secrets.BARKKEY }}" -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' -d 'title=Action%20Status&body=Packages%20-%20compile%20finished!&group=GithubAction&icon=https://github.com/isSuperman/WrtFactory/blob/15f2afc79edd2340f46f87d415e6fc3bfae56930/images/barkGroupLogo.jpeg?raw=true'

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: IPQ60xx_package
          path: openwrt/bin

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.artifact.outputs.release_tag }}
          body: "new packages"
          files: openwrt/artifact/package/*
          
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
         retain_days: 1
         keep_minimum_runs: 3

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
         keep_latest: 3
         delete_tags: true
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
