
name: test

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  SPEND_TIME: spend_time_formate.sh
  COMMIT_INFO: commit_formate.sh
  ETA: ETA_formate.sh
  TZ: Asia/Shanghai

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        echo "START_DATE=$(date +%s)"  >> $GITHUB_ENV
        sleep 10s
        echo "END_DATE=$(date +%s)"  >> $GITHUB_ENV

    - name: Generate time
      id: test
      run: |
        dts=`expr ${{ env.START_DATE }} + 9000`
        dt_day=`date -d @$dts "+%d"`
        dt_hour=`date -d @$dts "+%H"`
        dt_time=`date -d @$dts "+%H:%m"`
        echo "time is ${dt_time}"
        curl -sL https://git.io/eta_formate_sh > $ETA
        chmod +x $ETA
        ./$ETA $dt_day $dt_hour > dta_desc.log
        echo "$(cat dta_desc.log) $dt_time" > dt_str.log
        echo "DT=$(cat dt_str.log)" >> $GITHUB_ENV
        cd openwrt
        curl -sL https://git.io/commit_formate_sh > $COMMIT_INFO
        chmod +x $COMMIT_INFO
        ./$COMMIT_INFO immortalwrt lean-lede
        echo "DATE_INFO=$(cat day3.log)" >> $GITHUB_ENV
        
    - name: Cau Spend Time
      id: spend_time
      run: |
         echo "预计${{ env.DT }}完成"
         cd openwrt
         curl -sL https://git.io/spend_time_formate_sh > $SPEND_TIME
         chmod +x $SPEND_TIME
         ./$SPEND_TIME ${{ env.START_DATE }} ${{ env.END_DATE }} 2>&1 | tee cau_time.log
         echo "SPEND_TIME=$(cat cau_time.log)" >> $GITHUB_ENV
        
    - name: Cau Spend Time
      id: caculate
      run: |
       
        
        curl -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage' -H 'Content-Type: application/x-www-form-urlencoded' --data-binary $'parse_mode=MarkdownV2&chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&disable_web_page_preview=true&text=*Openwrt Update Checker：*\n\n⚙️ 固件开始编译\.\.\.\.\n🔮 预计${{ env.DT }}完成\n\n*What\'s New*\n${{ env.DATE_INFO }}\n\n耗时：${{ env.SPEND_TIME }}' 

        
