#
# Copyright (c) 2021 isSuperman
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/isSuperman/WrtFactory
# Description: Build Wrt Firmware using GitHub Actions
#

name: Test

on:
  # repository_dispatch:
  workflow_dispatch:
  
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: AX3600
  SPEND_TIME: spend_time_formate.sh
  COMMIT_INFO: commit_formate.sh
  ETA: ETA_formate.sh
  UPLOAD_RELEASE: true
  UPLOAD_FIRMWARE: true
  UPLOAD_NETDISK: false
  UP_COW: true
  UP_FIO: true
  UP_LIT: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout
      uses: actions/checkout@main

      
    - name: Push Notification
      run: |
        cd config
        curl https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMediaGroup\
          --data-binary $'chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&media=[{"caption":"[Pixiv50](https://pixiv50.com/)","parse_mode":"MarkdownV2","type":"photo","media":"https://pixiv50.com/static/images/wcldpgn/6203904_82693450_p0.jpg"},{"type":"photo","media":"https://www.pixiv50.com/static/images/iamcnqu/3371956_83774670_p0.jpg"}]'