#
# Copyright (c) 2021 isSuperman
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/isSuperman/WrtFactory
# Description: Build Wrt Firmware using GitHub Actions
#

name: Test

on:
  # repository_dispatch:
  workflow_dispatch:
  
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: AX3600
  SPEND_TIME: spend_time_formate.sh
  COMMIT_INFO: commit_formate.sh
  ETA: ETA_formate.sh
  UPLOAD_RELEASE: true
  UPLOAD_FIRMWARE: true
  UPLOAD_NETDISK: false
  UP_COW: true
  UP_FIO: true
  UP_LIT: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout
      uses: actions/checkout@main

    - name: GetUrl
      run: |
        echo "123123" > 1.log
        # curl -g https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMediaGroup?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}\&media=\[{"caption":"固件列表","parse_mode":"MarkdownV2","type":"document","media":"./1.zip"},{"type":"document","media":"./2.zip"}\]
        curl -sSX POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument\
         -H "Content-Type: application/x-www-form-urlencoded" -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -F document=@"1.log" -F caption=\n\n_测试内容_ -F parse_mode=MarkdownV2
